### ISSUE TITLE
Divide each store to its own crate

### ISSUE THREAD

**Issue by czocher** [maxcountryman/tower-sessions#102]
This is related to the same problem we had in `axum_login` - since `cargo` tries to resolve all the dependencies (even the one behind features) immediately, having lots of dependencies with non-additive/conflicting sub-dependencies can cause problems.

An example problem would be trying to implement stores for `sqlx` and `rusqlite` which share a `libsqlite3-sys` dependency - either we make them both happy by having the lowest common denominator for both crates or we can't do anything.

Dividing the stores into separate crates would solve this problem completely.

**Comment by maxcountryman** [comment]
Since we're publishing separate crates currently, does this mean that we should not re-export those crates via feature flags from the main crate? (I think this will lead to the issue you're describing.)

**Comment by czocher** [comment]
Yep I strongly believe since they are dependencies, cargo will load them all no matter the feature flags, but best to confirm it with a test.

**Comment by maxcountryman** [comment]
That being the case, I don't think it'll be too difficult to move toward removing the feature flags since we're done the work of physically separating stores into their own crates.

It's maybe also worth taking a second look at `sqlx` and how they approach this: I think they're able to get away with this because there's no problem with all SQL engines being enabled at the same time.

**Comment by maxcountryman** [comment]
@czocher were you able to determine that the feature flags indeed cause the interaction that you mentioned here? If so, should we proceed by removing the feature flags in `tower-sessions` and instead have applications require stores as separate deps?

**Comment by czocher** [comment]
Unfortunately I didn't have the time to perform the test.
The easiest way to do it would be to switch the version of dependencies in a way that makes the subdependencies incompatible with one another.
The earliest I can try this test is in January though.

**Comment by maxcountryman** [comment]
I think from a UX perspective, it might be cleaner to require session stores as dependencies anyway, omitting the feature flags altogether.

One downside is that testing these stores might become more cumbersome. (Or perhaps we require the same set of stores we currently have as dependencies of the integration test suite.)
