### ISSUE TITLE
When adding an Axum layer:  "the trait `From<Box<(dyn StdError + std::marker::Send + Sync + 'static)>>` is not implemented for `Infallible`"

### ISSUE THREAD

**Issue by yodermk** [maxcountryman/tower-sessions#108]
Hi, I have an Axum app that I just updated from 0.6 to 0.7, and also switched from axum_sessions to this, since that was recommended. I believe I'm doing the same thing as your example and getting a weird compiler error on the line that adds the `SessionManagerLayer` to the `Router`.

```
error[E0277]: the trait bound `Infallible: From<Box<(dyn StdError + std::marker::Send + Sync + 'static)>>` is not satisfied
   --> src/main.rs:61:13
    |
60  |           .layer(
    |            ----- required by a bound introduced by this call
61  | /             SessionManagerLayer::new(session_store)
62  | |                 .with_secure(false)
    | |___________________________________^ the trait `From<Box<(dyn StdError + std::marker::Send + Sync + 'static)>>` is not implemented for `Infallible`
    |
    = help: the trait `From<!>` is implemented for `Infallible`
    = note: required for `Box<(dyn StdError + std::marker::Send + Sync + 'static)>` to implement `Into<Infallible>`
note: required by a bound in `Router::<S>::layer`
   --> /Users/micahyoder/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.1/src/routing/mod.rs:238:50
    |
233 |     pub fn layer<L>(self, layer: L) -> Router<S>
    |            ----- required by a bound in this associated function
...
238 |         <L::Service as Service<Request>>::Error: Into<Infallible> + 'static,
    |                                                  ^^^^^^^^^^^^^^^^ required by this bound in `Router::<S>::layer`
```

The session_store is being set up like this:

```
    let session_store = MemoryStore::default();
    let session_layer = SessionManagerLayer::new(session_store)
        .with_secure(false);
```

Am I doing something wrong or is this a bug?  Thanks.

**Comment by maxcountryman** [comment]
Hi, thanks for your note. Can you share your code so we can take a closer look?

**Comment by yodermk** [comment]
Ok, I think I got it. I actually missed the `ServiceBuilder` and was trying to add the `SessionManagerLayer` directly to the router.  Also, when I tried the `ServiceBuilder` without the `HandleErrorLayer`, I got the exact same error adding the service builder to the router.

**Comment by maxcountryman** [comment]
Glad to hear that fixed it for you. If there's any improvements we can make to the docs, happy to incorporate your feedback.

**Comment by connorskees** [comment]
As an additional data point, I ran into this same issue when upgrading from `axum-sessions` to `tower-sessions`. From an API perspective, is it possible to make usage of the `ServiceBuilder` from `tower` optional? Otherwise, is it possible to not require the `HandleErrorLayer` on the `ServiceBuilder`? The API feels more verbose than necessary because of these two things.

**Comment by maxcountryman** [comment]
You don't need the error handler if you don't use axum. But for axum, you'll need it or something like it because axum middleware cannot be fallible.
