### ISSUE TITLE
Facilitate custom `SessionStore` implementation testing

### ISSUE THREAD

**Issue by rynoV** [maxcountryman/tower-sessions#121]
Thanks for making this!

With the latest version (`0.8`) it seems custom session store implementations are not possible because the `Result` and `Error` types are not exported. This fixes it for me:

```diff
modified   tower-sessions-core/src/lib.rs
@@ -4,7 +4,7 @@ pub use tower_cookies::cookie;
 pub use self::{
     service::{SessionManager, SessionManagerLayer},
     session::{Expiry, Session},
-    session_store::{CachingSessionStore, ExpiredDeletion, SessionStore},
+    session_store::{CachingSessionStore, ExpiredDeletion, SessionStore, Result, Error},
 };
 
 #[cfg(feature = "axum-core")]
```

Additionally, the latest changes have made it more challenging to test my custom implementation because I was previously relying on the `Serialize` instance of `Session` to check for equality in tests, but now the serialization is done through `Record`, and `Session` doesn't have a public API to access the `Record`. Maybe we could add a `Serialize` implementation to `Session` that just delegates to the `Record` serializer?

I've made a SurrealDB store, you can see what I'm trying to do in my tests here: https://github.com/rynoV/tower-sessions-surrealdb-store/blob/master/src/lib.rs. Right now I've just set `Session::get_record` to public (in my local copy) to facilitate my tests.

**Comment by maxcountryman** [comment]
Thanks for spotting this. Happy to accept a PR and publish a fix.

**Comment by maxcountryman** [comment]
Regarding the types, I do think we should leave them as they are so they're name-spaced. For example, they're used like [this](https://github.com/maxcountryman/tower-sessions/blob/c147da203a8de9f31f03100560a4637f8d157c5e/redis-store/src/lib.rs#L66) in our other store crates.

I'd also prefer we not implement `Serialize` for `Session`: this might be a confusing interface since we'd only intend to use it for testing. Can you go into more detail regarding the testing pattern you're having difficulty with?

**Comment by rynoV** [comment]
> Regarding the types, I do think we should leave them as they are so they're name-spaced

Makes sense thanks, I didn't think of importing them like that before so that's all good.

> I'd also prefer we not implement Serialize for Session: this might be a confusing interface since we'd only intend to use it for testing. Can you go into more detail regarding the testing pattern you're having difficulty with?

Essentially I'm trying to round-trip test the sessions, so `create session -> save -> load -> check equality`, so the first issue was I couldn't see a way to create a session then get its record so that I can pass it to `save`, but now I see that I can use `session.save` for this.

The next issue is I can't see a way to check that the original session from `create session` is equal to the session after the `load` step:

- Originally I was thinking if there was a `PartialEq` instance, then I could make a clone of the original session before it's mutated, then use `session.load` on the original, but I think the clone would be mutated as well since everything is in `Arc`s.
- The other way would be to check for equality between the record returned from `SessionStore::load` and the record of the original session, but that original record isn't accessible (without first saving then loading the session, but that defeats the purpose of the test)
- I could also try implementing my own equality check using `get_value`, but I think this would have the same issue as the first point re cloning, and it would be preferable to have a "canonical" equality check so that my implementation doesn't fall behind when changes are made to this package

I'm not sure of the best way to handle this, maybe have a way to make a deep copy of a session and an implementation of `PartialEq`?

**Comment by maxcountryman** [comment]
I'm not opposed to PartialEq. That said I think it's also worth thinking a bit more about what's valuable to test here: presumably we want to ensure that nothing strange is happening when SurrealDB is saving and loading the session so if you could verify the session saves the data you expect and then later a session can be created using the same id which loads the expected data I wonder if that achieves what you're aiming for? I think this could all be done using the session methods and manually constructing a session via the id a la what the middleware does.

**Comment by rynoV** [comment]
Thanks for taking the time to discuss.

I think at the end of the day I'm trying to get some tests such that, when updating `tower-sessions-core`, if my implementation no longer meets the spec then there's either a test failure or compiler error, which is why having either `PartialEq` for `Session` or `Serialize` would be great.

> if you could verify the session saves the data you expect and then later a session can be created using the same id which loads the expected data I wonder if that achieves what you're aiming for

If I'm understanding you correctly you're suggesting something like checking equality by running `get_value` for each expected key and checking the other properties as well, which isn't ideal because it's still not checking full equality (what if a new key in the session map gets added somehow in a bug in my implementation, then the test still passes; unlikely but preferrable to avoid the possibility), and if for example a new property is added to `Session` in the future, there wouldn't be any failure telling me I need to update my equality check.

I'm still fairly new to rust so I'm not sure the best way to do this, but maybe adding a `Serialize` instance under a `#[cfg(test)]` flag, or a `fn check_session_equality` under the same flag?

Or if there was a `PartialEq` instance that would check for full equality, then I could roundtrip test by

```
create_session(session1, session_create_config)
-> session1.save
-> session1.load
-> create_session(session2, session_create_config, session1.id)
-> session1 == session2
```

Although that's still not ideal because there's no (automated) guarantee that `Session::save/load` actually calls my `SessionStore::save/load` implementations.

I find this type of test very valuable because it's simple, fast, and tests right at the source, so it would be great if this library could support some built-in way to check "equality" of sessions. "Equality" can be defined however is appropriate for the spec, it doesn't have to be full equality, my main request is for some canonical way to check this equality so that my tests will fail appropriately when the library is updated.

**Comment by maxcountryman** [comment]
My feeling is feature flags aren't really the best way to enable what you're after. PartialEq is likely a more idiomatic approach.

> Although that's still not ideal because there's no (automated) guarantee that Session::save/load actually calls my SessionStore::save/load implementations.

It feels like this is outside the scope of a store. If Session::save doesn't do that it's a bug in tower_session_core, right?

**Comment by rynoV** [comment]
Yeah I think it's pretty unlikely that `Session::save/load` come to mean something completely different, so `PartialEq` should be good.

For the implementation, does something like this seem appropriate? It's intended to check the values of each property except for `store` (I didn't think the store was important for two sessions to be equal, because I think the idea is the store implementation could be swapped arbitrarily, correct me if I'm wrong). If it's okay let me know and I can open a PR

```diff
modified   tower-sessions-core/src/session.rs
@@ -69,6 +69,16 @@ pub struct Session {
     is_modified: Arc<AtomicBool>,
 }
 
+impl PartialEq for Session {
+    fn eq(&self, other: &Self) -> bool {
+        use std::sync::atomic::Ordering;
+        *self.session_id.lock() == *other.session_id.lock()
+            && *self.record.blocking_lock() == *other.record.blocking_lock()
+            && *self.expiry.lock() == *other.expiry.lock()
+            && self.is_modified.load(Ordering::SeqCst) == other.is_modified.load(Ordering::SeqCst)
+    }
+}
+
 impl Session {
     /// Creates a new session with the session ID, store, and expiry.
     ///
@@ -875,7 +885,7 @@ impl FromStr for Id {
 
 /// Record type that's appropriate for encoding and decoding sessions to and
 /// from session stores.
-#[derive(Debug, Clone, Serialize, Deserialize)]
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
 pub struct Record {
     pub id: Id,
     pub data: Data,
```

**Comment by maxcountryman** [comment]
Unfortunately that implementation is very likely to panic. See this note in blocking_lock:

> This function panics if called within an asynchronous execution context.

It's somewhat tricky because there's not a great way to work around the fact the record access is necessarily async (that's why the session methods are async now, for example).

Perhaps the better way forward is to make the record accessible publicly and then use the session methods to compare each attribute you want to test against.

**Comment by rynoV** [comment]
Thanks again for your time with this.

Yeah I noticed that panic when I tried to implement my tests. I also realized it's a lot more difficult to implement the `create_session` part of my roundtrip plan than I thought, and testing that would probably be pretty flakey because getting it right means basically figuring out all the implementation details of `Session` to perfectly recreate sessions in certain states.

I think I was stuck in the mindset of testing roundtrips of `Session`s, but I think testing just the roundtrips of `Record`s is fine, because really that's all the `SessionStore` deals with in the current version. So basically as long as `load` returns the same `Record` that was passed into `save`, then the `SessionStore` implementation is correct.

So just adding a `PartialEq` instance to `Record` makes the type of testing I'm looking for possible, would that be okay?

**Comment by maxcountryman** [comment]
> So just adding a PartialEq instance to Record makes the type of testing I'm looking for possible, would that be okay?

This makes sense to me. Thank you! 🙏

**Comment by maxcountryman** [comment]
Also as an aside: if it's all right with you, could we add a link in the README to your surrealdb store when it's published? I think other folks would find it useful and I'd be happy to keep a catalog of the session store implantations for discovery purposes.

**Comment by rynoV** [comment]
Great! Made a PR, and yeah I'll make another PR  to add the link once it's published.
