### ISSUE TITLE
Still waiting on your answer regarding #59 (Diesel store implementation)

### ISSUE THREAD

**Issue by weiznich** [maxcountryman/tower-sessions#142]
I'm opening this issue as I still wait on your answer regarding to https://github.com/maxcountryman/tower-sessions/pull/59. It is quite frustrating to be promised an answer soonish and not getting a response afterwards.

**Comment by weiznich** [comment]
Thanks for the fast response. I'm sorry, but I still feel that this does not address the question raised in https://github.com/maxcountryman/tower-sessions/pull/59#issuecomment-1790530807 whether you feel confident or not that the linked implementation would be maintainable for you.

**Comment by maxcountryman** [comment]
I will not be taking on the maintenance of any additional store crates.

That said, we have a growing ecosystem of third party store crates and I'd love to catalog those in the README as we've begun doing.

If you have additional questions, please do use the GitHub Discussions forum for those.
