### ISSUE TITLE
version 0.10.3 broke SemVer guarantees

### ISSUE THREAD

**Issue by qrilka** [maxcountryman/tower-sessions#160]
- [X] I have looked for existing issues (including closed) about this

## Bug Report

Version 0.10.3 added lifetime parameter to SessionManager - https://docs.rs/tower-sessions/latest/tower_sessions/service/struct.SessionManager.html
As per https://doc.rust-lang.org/cargo/reference/semver.html#trait-new-parameter-no-default this is a Major change and yet only a patch version was released
This e.g. breaks builds of `axum-login`

### Version

```
$ cargo tree | grep tower-sessions
│   ├── tower-sessions v0.10.3
│   │   ├── tower-sessions-core v0.10.3
│   │   ├── tower-sessions-memory-store v0.10.3
│   │   │   └── tower-sessions-core v0.10.3 (*)
```

### Platform

```
$ uname -a
Linux qdell-7080 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 GNU/Linux
```

### Description

As specified, failed in a project depending on axum-login-0.13

**Comment by maxcountryman** [comment]
This seems like it demonstrates the issue: https://github.com/maxcountryman/axum-login/issues/189

**Comment by maxcountryman** [comment]
The release is yanked so that closes this ticket.

That said, we'll put together a new release either hardcoding the static lifetime or incrementing the minor version.
