### ISSUE TITLE
set_expiry() does not work 

### ISSUE THREAD

**Issue by Katze864** [maxcountryman/tower-sessions#174]
- [x] I have looked for existing issues (including closed) about this

### Version

tower-sessions v0.11.0
tower-sessions-core v0.11.0
tower-sessions-memory-store v0.11.0
tower-sessions-sqlx-store v0.11.0

### Platform

Windows 10 64-bit

### Description

When using `set_expiry` on a session the new expiry date is not saved in the session store. This seems to be because `set_expiry` updates the field `expiry`, but not the record; only the record is sent to the session store. 

I tried this code:
```
let expired_at = OffsetDateTime::now_utc().saturating_add(Duration::days(60));
session.set_expiry(Some(Expiry::AtDateTime(expired_at)));
```

I expected to see this happen: 
The expiry date in the database should be updated, and the session should last 60 days. 

Instead, this happened: 
The expiry date in the database was updated according to the previous expiry (OnInactivity) and the session expired. 
The expiry time of the cookie was correctly updated, this resulted in a warning on the server:
`WARN  [tower_sessions_core::session] possibly suspicious activity: record not found in store`

**Comment by maxcountryman** [comment]
Please provide a minimal example that reproduces what you're seeing.

**Comment by Katze864** [comment]
This seems a little long for a minimal example, feedback on how to do it better would be welcome.
On reloading the page http://127.0.0.1:3000/ after more than 2 seconds the warning `WARN  [tower_sessions_core::session] possibly suspicious activity: record not found in store` is shown, which indicates that the session has expired and has been deleted. 

```
use std::net::SocketAddr;

use axum::{response::IntoResponse, routing::get, Router, middleware, middleware::Next, http::{Request, Response}, body::Body as AxumBody};
use time::{OffsetDateTime, Duration};
use tower_sessions::{Expiry, Session, SessionManagerLayer};
use sqlx::sqlite::SqlitePoolOptions;
use tower_sessions_sqlx_store::SqliteStore;


async fn change_expiry(
    session: Session, 
    request: Request<AxumBody>,
    next: Next,
) -> Response<AxumBody> {
    
    //modify the session, so it gets stored to the db
    session.insert("last_accessed", OffsetDateTime::now_utc()).await.unwrap();

    // change the session expiry
    let expired_at = OffsetDateTime::now_utc().saturating_add(Duration::days(60));
    session.set_expiry(Some(Expiry::AtDateTime(expired_at)));

    let response = next.run(request).await;
    response
}

#[tokio::main]
async fn main() {
    simple_logger::init_with_level(log::Level::Warn)
        .expect("couldn't initialize logging");

    let pool = SqlitePoolOptions::new()
        .connect("sqlite:database.db")
        .await
        .expect("Could not make pool.");

    let session_store = SqliteStore::new(pool.clone());
    let session_layer = SessionManagerLayer::new(session_store)
        .with_secure(false)
        .with_expiry(Expiry::OnInactivity(Duration::seconds(2)));

    let app = Router::new().route("/", get(handler))
        .layer(middleware::from_fn(change_expiry))
        .layer(session_layer);

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    let listener = tokio::net::TcpListener::bind(&addr).await.unwrap();
    axum::serve(listener, app.into_make_service())
        .await
        .unwrap();
}

async fn handler() -> impl IntoResponse {
    format!("HI")
}

```

**Comment by maxcountryman** [comment]
Thank you, this is very helpful.

I've put together a test case and am working on a patch.

**Comment by maxcountryman** [comment]
This should be address in the `0.11.1` release.

**Comment by Katze864** [comment]
Thanks
