### ISSUE TITLE
Max-Age of Cookie not updates on set_expiry()

### ISSUE THREAD

**Issue by Katze864** [maxcountryman/tower-sessions#178]
- [x] I have looked for existing issues (including closed) about this

### Version

tower-sessions v0.11.1
tower-sessions-core v0.11.1
tower-sessions-memory-store v0.11.1

### Platform

Windows 10 64-bit

### Description

When using `set_expiry` on a session that was created through the SessionManagerLayer without a default expiry the max-age attribute of the cookie is not set. This seems to be because of the match condition in `build_cookie()`, which considers the expiry set for SessionManagerLayer and not for the session: 
```
if !matches!(self.expiry, Some(Expiry::OnSessionEnd) | None) {
    cookie_builder = cookie_builder.max_age(expiry_age);
}
```

Example: 

```
use std::net::SocketAddr;

use axum::{response::IntoResponse, routing::get, Router, middleware, middleware::Next, http::{Request, Response}, body::Body as AxumBody};
use time::{OffsetDateTime, Duration};
use tower_sessions::{Expiry, Session, SessionManagerLayer};
use sqlx::sqlite::SqlitePoolOptions;
use tower_sessions_sqlx_store::SqliteStore;


async fn change_expiry(
    session: Session, 
    request: Request<AxumBody>,
    next: Next,
) -> Response<AxumBody> {
    //modify the session, so it gets stored
    session.insert("last_accessed", OffsetDateTime::now_utc()).await.unwrap();

    // change the session expiry
    let expired_at = OffsetDateTime::now_utc().saturating_add(Duration::seconds(2));
    session.set_expiry(Some(Expiry::AtDateTime(expired_at)));

    let response = next.run(request).await;
    response
}

#[tokio::main]
async fn main() {
    simple_logger::init_with_level(log::Level::Warn)
        .expect("couldn't initialize logging");

    let pool = SqlitePoolOptions::new()
        .connect("sqlite:database.db")
        .await
        .expect("Could not make pool.");

    let session_store = SqliteStore::new(pool.clone());
    let session_layer = SessionManagerLayer::new(session_store)
        .with_secure(false);

    let app = Router::new().route("/", get(handler))
        .layer(middleware::from_fn(change_expiry))
        .layer(session_layer);

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    let listener = tokio::net::TcpListener::bind(&addr).await.unwrap();
    axum::serve(listener, app.into_make_service())
        .await
        .unwrap();
}

async fn handler() -> impl IntoResponse {
    format!("HI")
}
```

I expected to see this happen: 
The max-age attribute of the cookie is set to two seconds. 

Instead, this happened: 
The max-age of the cookie is Session. In the database the expiry time was correctly updated, this resulted in a warning on reload:
`WARN  [tower_sessions_core::session] possibly suspicious activity: record not found in store`

**Comment by maxcountryman** [comment]
> When using set_expiry on a session that was created through the SessionManagerLayer without a default expiry the max-age attribute of the cookie is not set.

The default here is then to not set `Max-Age` at all, aka to create a "session" cookie that will expire upon session close.

As I mentioned on the discussion thread, `Session::set_expiry` isn't capable of overloading the layer default after the first request. In other words, it'll set the expiry and persist that to the store, but when the session is loaded for the next request there's no way for us to initialize it with the new expiry and so the default is then used.

I think to fix this we need to rework the expiration interface (and thereby the `Record` itself).

**Comment by Katze864** [comment]
It's not about loading the session on the next request, but setting the cookie correctly with the response. The way it is handled now, whether the `Max-Age` is set depends on the expiry set from the default layer, which might be changed during the request. The new expiry duration is passed on to the `build_cookie()` function in `SessionConfig`, but ignored if the default expiry was `None`, or `OnSessionEnd`. This leads to an inconsistency between the cookie and the session stored on the backend. 
It could be solved by passing the new expiry instead of the duration and setting the `Max-Age` accordingly. 
As `build_cookie()` is a private function that should not cause any problems.  

The lines
```
let expiry_age = session.expiry_age();
let session_cookie = session_config.build_cookie(session_id, expiry_age);
```
in `SessionManager` would change to 
```
let expiry = session.expiry();
let session_cookie = session_config.build_cookie(session_id, expiry);
```

**Comment by maxcountryman** [comment]
Okay I think we can make that change. It won't address the larger issue but if that fixes it for your use case I'm happy to add it. Would you want to put together a PR? I can cut a new release once that's merged.
