### ISSUE TITLE
Version 0.12.0 not compatible with redis-store 0.11.0

### ISSUE THREAD

**Issue by Gradlon** [maxcountryman/tower-sessions#185]
- [x] I have looked for existing issues (including closed) about this

## Bug Report
When I try to instantiate a session layer with Redis, I get the following error
```
the trait bound `RedisStore<RedisPool>: SessionStore` is not satisfied
the following other types implement trait `SessionStore`:
  MemoryStore
  CachingSessionStore<Cache, Store>
  ````
The issue only apear with version 12, 11 works fine.
As far as i understand it the problem arises here

```
#[derive(Debug, Clone)]
pub struct SessionManagerLayer<Store: SessionStore, C: CookieController = PlaintextCookie> {
    session_store: Arc<Store>,
    session_config: SessionConfig<'static>,
    cookie_controller: C,
}
```
### Version
```
tower-sessions = { version = "0.12.0",  features = ["signed", "private"]}
tower-sessions-redis-store = { version = "0.11.0"}
fred = { version = "7.0.0" }
axum-login = "0.15.0"

<!--
List the versions of all `tower-sessions` crates you are using. The easiest way to get
this information is using `cargo tree`:

```
 - tower-sessions v0.12.0
    - tower-sessions-core v0.12.0
       -  tower-sessions-memory-store v0.12.0
       -  tower-sessions-core v0.12.0 (*)
    - tower-sessions-core v0.11.1
- tower-sessions v0.12.0 (*)
- tower-sessions-redis-store v0.11.0

-->

### Platform
MACOS Apple silicone

### Crates

tower-sessions = { version = "0.12.0",  features = ["signed", "private"]}
tower-sessions-redis-store = { version = "0.11.0"}
fred = { version = "7.0.0" }
axum-login = "0.15.0"

### Description
whene using the latest versions of the listed crates I get this error.
Reverting all down to the previous major solves the problem
Example:

This works.
```
tower-sessions = { version = "0.11.1",  features = ["signed", "private"]}
tower-sessions-redis-store = { version = "0.11.0"}
fred = { version = "7.0.0" }
axum-login = "0.14.0"
```
This fails
```
tower-sessions = { version = "0.12.0",  features = ["signed", "private"]}
tower-sessions-redis-store = { version = "0.11.0"}
fred = { version = "7.0.0" }
axum-login = "0.15.0"
```

Code used:
```
// pub async fn create_session() -> SessionManagerLayer<RedisStore<RedisPool>, SignedCookie> {
pub async fn create_session() -> SessionManagerLayer<RedisStore<RedisPool>> {
    let key = Key::generate();
    print!("Session key {:?}", key);
    let session_store = RedisStore::new(database::redis::new_pool().await);
    let session_layer = SessionManagerLayer::new(session_store)
        .with_secure(true)
        .with_expiry(Expiry::OnInactivity(Duration::seconds(config::SETTINGS.security.session_expiry)));
        // .with_signed(key);
    session_layer
}

use fred::clients::RedisPool;
use time::Duration;
// use tower_cookies::Key;
use tower_sessions::{Expiry, SessionManagerLayer};
use tower_sessions_redis_store::RedisStore;
use super::database;
use crate::core::config;
use tower_sessions::{cookie::{Cookie, Key}, service::SignedCookie};
```

**Comment by maxcountryman** [comment]
`RedisStore` has not been updated and cannot be used with the latest tower-sessions release.

Currently `fred` doesn't support transactions over a generic client interface. My understanding is they are planning an update soon that addresses this. 

Unfortunately without transactions it's difficult to correctly implement `create`.
