### ISSUE TITLE
MokaStore, insert into session does not invalidate cached value

### ISSUE THREAD

**Issue by beckend** [maxcountryman/tower-sessions#20]
I am using https://github.com/maxcountryman/tower-sessions/blob/main/examples/moka-postgres-store.rs

Without the moka store, inserting then fetching the value is no problem, everything is updated as it should, however the design of insert must invalidate the cache, right now I tried to use the example and `session.insert` and later in another route fetching the data gets you the stale cached value.

**Comment by maxcountryman** [comment]
Can you provide an example?

Currently the session itself will be filtered by the active flag. (However this design will likely change in the future such that stores must enforce this semantic on their own.) This means a session that's expired will not be available in a route once it's been loaded.

**Comment by beckend** [comment]
```rust
async fn handler1(session: Session) -> impl IntoResponse {
    let counter: Counter = session
        .get(COUNTER_KEY)
        .expect("Could not deserialize.")
        .unwrap_or_default();

    session
        .insert(COUNTER_KEY, counter.0 + 1)
        .expect("Could not serialize.");

    format!("Current count: {}", counter.0)
}

// later in app hitting:
async fn handler2(session: Session) -> impl IntoResponse {
    let counter: Counter = session
        .get(COUNTER_KEY)
        .expect("Could not deserialize.")
        .unwrap_or_default();

   // the insert did not update the value, you get the old value
    format!("Current count: {}", counter.0)
}
```

This works fine for postgresql, moka does not.

**Comment by maxcountryman** [comment]
So far I'm not able to replicate a discrepancy between `CachingSessionStore` and another store. Note the codepath is the same: both save methods are invoked in sequence in the save future of the caching store.

Can you provide a complete example that clearly demonstrates the issue you're seeing? I would like to be able to replicate it locally ideally.

**Comment by beckend** [comment]
I have been sitting here debugging my code, I am doing redirects and various XHR requests and my handlers and then gets a new session ID which was the cause not having an old state, sorry for the noise.
