### ISSUE TITLE
The session expiry is never loaded from store

### ISSUE THREAD

**Issue by longsleep** [maxcountryman/tower-sessions#206]
- [ x] I have looked for existing issues (including closed) about this

## Bug Report

The session expiry date is set in to record at https://github.com/maxcountryman/tower-sessions/blob/05517aaf3f1caf7fc548b3eaf831734b37aab96a/tower-sessions-core/src/session.rs#L667 and thus stored in the store. Though when loading the record from the store, the expiry data is not set back so that it becomes available through the session API functions which use `self.inner.expiry`. Means any session which is loaded from the store has expiry None which essentially will use the now + default duration for age checks (https://github.com/maxcountryman/tower-sessions/blob/05517aaf3f1caf7fc548b3eaf831734b37aab96a/tower-sessions-core/src/session.rs#L577C58-L577C74).

I am a bit confused why this was not reported before. I would expect that the expiry is available after loading from the store. What would be point be to actually put it into the record if it is never used from there?

The tests in 

### Version

I am on 0.12.2.

**Comment by maxcountryman** [comment]
Take a closer look at the expiry methods and then note how they're used by the save method and record loading procedure.

If there's an aspect of the test suite that isn't covering a specific case, please demonstrate that with a patch to the tests.

**Comment by longsleep** [comment]
> Take a closer look at the expiry methods and then note how they're used by the save method and record loading procedure.

I did, there is no way to access Record.expiry_date through the https://github.com/maxcountryman/tower-sessions/blob/05517aaf3f1caf7fc548b3eaf831734b37aab96a/tower-sessions-core/src/session.rs#L69. The only function which could return it is `get_record` but it is private.

I have to store some additional timestamp in `Record.data`  to know how old a loaded session is.

> 
> If there's an aspect of the test suite that isn't covering a specific case, please demonstrate that with a patch to the tests.

There are no tests for the `Session.load` API or its expiry related functions. Also seems the recommended way to use this is via `tower_sessions::service::SessionManagerLayer` which always sets the expiration before loading sessions. This might be the intentional behavior and my scenario using `tower_sessions::session::Session` directly might be out of scope, but I still think it is very confusing not to load the expiry from the store when none is set when loading a session.

Changing this might have undesired consequences for existing useres of this package though, so I guess making a unit test for this makes no sense. Just sharing my thoughts here in case other people stumble over this.

**Comment by maxcountryman** [comment]
You seem to be confused: the `Record` type does not contain the `Expiry` type at all. There's no way to obtain `Expiry` from `Record`.

This was already discussed previously in #178.

**Comment by longsleep** [comment]
The record type does not contain the `Expiry` type - I never said that I did. The record type contains the expiraiton timestamp https://github.com/maxcountryman/tower-sessions/blob/05517aaf3f1caf7fc548b3eaf831734b37aab96a/tower-sessions-core/src/session.rs#L920. In my opinion, when loading the `Session` from the store, this value should be used to set the `Session`'s `inner.expiry` to `Exiry::AtDateTime` variant if the `inner.expiry` is None at load time.

Imo it is confusing that the `Session.get_expiry` returns some entirely unrelated "relative to now" timestamp when no expiry is set when creating the `Session` type (https://github.com/maxcountryman/tower-sessions/blob/05517aaf3f1caf7fc548b3eaf831734b37aab96a/tower-sessions-core/src/session.rs#L576).

I think simply using the `Record.expiry_date` when it is available after load from the store makes a lot of sense and would solve this confusion.

I don't know if people built software around the existing behavior, but at least with the most common use case through `SessionManagerLayer` this is not an issue as that code always sets expiry before loading the session and hence it is never None there.

**Comment by maxcountryman** [comment]
Please take this discussion to the previous threads.
