### ISSUE TITLE
Support `diesel` as database library

### ISSUE THREAD

**Issue by weiznich** [maxcountryman/tower-sessions#26]
Tower-sessions offers various sessions storages backed by relational databases. It only supports `sqlx` based connections for these stores. It would be great to allow other database connection types like that one provided by diesel/diesel-async as well, as users might prefer these for various reasons.

**Comment by maxcountryman** [comment]
Thanks for mentioning this. I've not used diesel in a long time but I'd be happy to accept a PR that adds this support.

**Comment by maxcountryman** [comment]
As per the discussion in #59, this will be best implemented as a standalone crate.
