### ISSUE TITLE
`std::option_env!("URL").unwrap()` in tests

### ISSUE THREAD

**Issue by avdb13** [maxcountryman/tower-sessions#31]
I don't know exactly whether this is a good title for the issue but I'm wondering how you manage to run tests for all databases without the hassle of setting them all up separately.

**Comment by maxcountryman** [comment]
The CI runner uses docker compose, as an example: https://github.com/maxcountryman/tower-sessions/blob/cbde7ea0818c5a7113d78c2738b566937857c3ad/tests/docker-compose.yml

Each database URL is defined as part of the workflow environment: https://github.com/maxcountryman/tower-sessions/blob/cbde7ea0818c5a7113d78c2738b566937857c3ad/.github/workflows/rust.yml#L12-L15

There probably could be some glue that would make this easier to run locally.

**Comment by avdb13** [comment]
Thanks! Will try this out tomorrow.
