### ISSUE TITLE
Feature Request: Companion Cookie

### ISSUE THREAD

**Issue by iJustErikk** [maxcountryman/tower-sessions#50]
Many client side apps log the user out after some time. I think they do this by checking if the session cookie is in the cookies (if its not httponly) or they check the existence of a some companion cookie. The purpose of the companion cookie is to verify if the session cookie exists without having access to the session cookie (it will have the same expiration and not be httponly).

The only way to do this with tower-sessions as is, is to add a companion cookie yourself or wait until your backend responds with 401. This would be a bit simpler and I think it would be a nice feature.

Suggested API Code Example:

`SessionManagerLayer::new(session_store).with_max_age(DURATION).with_name(SESSION_COOKIE_NAME).with_companion(true);
`

If with_companion is called without with_max_age, then it should have no effect and a warning should be logged.

I think this would be a useful feature and simple to implement. If this is a good idea, I can implement it when I get some time.

**Comment by maxcountryman** [comment]
Couldn't a client-side code call a route which deletes the session? Maybe you can describe the specific use case in a little more detail.

**Comment by iJustErikk** [comment]
Now that I think about it, I think this would be overkill in my use case (logging active user out say 5 minutes after they log in, even if they leave the tab). I don't really need to log the user out arbitrarily close the session cookie expiring. 

I'll close this.
