### ISSUE TITLE
Support auto-prolonging sessions

### ISSUE THREAD

**Issue by teenjuna** [maxcountryman/tower-sessions#57]
# Problem

As I understand it, right now, even if a session was modified, it's `expiration_time` is not updated automatically. As a result, end user will lose their session even if they were actively interacting with web server and their session was modified frequently.

To avoid that, current API provides `set_expiration_time` and `set_expiration_time_from_max_age` methods. This is useful, but I think the crate can provide some additional functionality to make common use cases easier.

# Proposition

First proposition is to allow devs to opt-in for auto-prolonging of the modified sessions, meaning that `expiration_time` of sessions marked as `modified` should be set to now + the duration set with `SessionManagerLayer::with_max_age`. This could be enabled with a new method `SessionManagerLayer::with_auto_prolong(bool)`.

Second proposition is to add a new method for session, namely `Session::prolong()` that will allow to manually do the same thing in case the session itself was not modified, but the user it's linked to (for example) was. It's just a convenient alternative to `Session::set_expiration_time_from_max_age` that doesn't require to move `max_age`'
s `Duration` to a constant in our own program.

Though there's a small problem with this approach. Consider that dev used `set_expiration_time*` method with auto-prolong enabled. The session is marked as modified, therefore session manager will rewrite the `expiration_time` set by dev. I think that the best way to solve that is to set `expiration_time` to a `max(session.expiration_time, now+max_age)`.

**Comment by maxcountryman** [comment]
I would like to follow [the semantics of the Django implementation](https://docs.djangoproject.com/en/5.0/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase.get_expiry_age).

This likely requires breaking changes, but that's okay.

**Comment by teenjuna** [comment]
So, instead of a setting a duration, one would set a value of an enum that will look something like this:
```rust
enum SessionExpiry {
    // Duration after inactivity (automatically prolonged after session modification).
    Duration(Duration),
    // Exact time (stays constant even if session was modified).
    DateTime(DateTime),
    // Expired after browser is closed.
    BrowserSession,
}
```

If that's right, then I like it!

**Comment by maxcountryman** [comment]
Exactly, I have something like this:

```rust
/// Session expiry configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SessionExpiry {
    /// Expire the session when it's been inactive for the given number of
    /// seconds.
    InactiveFor(usize),

    /// Expire the session when the given `OffsetDateTime` is reached.
    AtExact(OffsetDateTime),

    /// Expire the session when the browser is closed.
    Closed,
}```

But I'm not too attached to the variant names, so happy to adjust those.

**Comment by teenjuna** [comment]
I'm kind of liking my naming a bit more, but the `BrowserSession` could be improved. Maybe `WhileBrowserOpen` or something like this.

Also, please take duration, not integer seconds. It's just a nicer API, and can be converted to integer seconds internally if needed.
