### ISSUE TITLE
Allow to define the session cookie name

### ISSUE THREAD

**Issue by czocher** [maxcountryman/tower-sessions#73]
Currently it's hardcoded to `tower.sid` here: https://github.com/maxcountryman/tower-sessions/blob/0f953c9d26832858783bf458cc67713905aed7fe/src/service.rs#L56

Having a specific session name leaks information about the backend implementation. This should be set to something generic by default (like "id") and preferably changeable by the user (see the OWASP requirements: https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-id-name-fingerprinting).

**Comment by maxcountryman** [comment]
Since we can [configure this](https://github.com/maxcountryman/tower-sessions/blob/0f953c9d26832858783bf458cc67713905aed7fe/src/service.rs#L289) when we create the manager or layer, should this ticket be for updating the "tower.sid" default to "sid"?

**Comment by czocher** [comment]
You're right, I didn't notice it's configurable, so yes, just updating to to a generic `sid` would be enough.
