### ISSUE TITLE
Problems around OnInactivity session expiry

### ISSUE THREAD

**Issue by martinetd** [maxcountryman/tower-sessions#74]
Hello,

I was following #60 a few weeks ago and was glad to see it already implemented, thanks for the quick work!

On trying the new version of tower-sessions in my server, I've noticed the max-age attribute is still set, e.g. this code:
```
    let session_store = MokaStore::new(None);
    let session_service = ServiceBuilder::new()
        .layer(HandleErrorLayer::new(|_: BoxError| async {
            StatusCode::BAD_REQUEST
        }))
        .layer(
            SessionManagerLayer::new(session_store)
                .with_secure(false)
                .with_expiry(Expiry::OnInactivity(Duration::seconds(10))),
        );
```

yields this reply on login:
```
set-cookie: tower.sid=79af9808-fb5d-457f-bc11-c096f6bc24ec; HttpOnly; SameSite=Strict; Path=/; Max-Age=9
```

So that even spamming requests every few seconds that each send the cookie, after 10 seconds the browser will stop sending the cookie and you'll stop being connected at this point from login.
I believe that would only work if we keep sending a new set-cookie with the same value and a new max-age on every single request? (my server uses session.get on every request, but not session.insert as I see in examples -- perhaps the current code would reset the cookie if insert was made?)
But I also just don't see the point of setting a max age here: it's something the server should enforce; if an old cookie is sent we just shouldn't find the session so it should behave as if nothing had been sent.

... Speaking of which I tried with curl:
```
curl -H 'Cookie: tower.sid=79af9808-fb5d-457f-bc11-c096f6bc24ec' https://myserver
```
and the server still happily found the session despite the time being long overdue; I thought the point of MokaStore vs MemoryStore was that Moka would properly clean up expired sessions ?
Should I try something else e.g. in-memory sqlite? (I picked moka because the binary size was smaller with it than sqlite as this is for an embedded product and I'd very much like to keep the server small...)
Ah, I see tower-sessions 0.3.3 did properly remove old entries, so this looks like a new bug.

(While I'm here, I think it'd be great API-wise to allow "seconds from now" as a possibility, e.g.
```
pub enum Expiry {
    OnSessionEnd, // browser session end
    OnInactivity(Duration), // duration from last request
    AfterDuration(Duration),  // duration from cookie being created
    AtDateTime(OffsetDateTime), // absolute date
 ```
I don't quite see how to use AtDateTime because the session manager layer is initialized at server startup, so it doesn't seem practical to update on every request...? Or is that something else I missed? Happy to fork this part of the topic to a discussion or something else; let's focus on "inactivity" not being inactivity in this issue if this is controvertial...)

**Comment by maxcountryman** [comment]
Hi, thanks for reaching out--happy to help here.

> perhaps the current code would reset the cookie if insert was made?

Correct. We follow the Django semantics here, which set a modified flag only when the session is updated. In other words, activity depends on something happening with the session, by default.

What I think you're looking for is a related but different feature we haven't implemented: configuration for session save behavior a la [`SESSION_SAVE_EVERY_REQUEST`](https://github.com/django/django/blob/f7389c4b07ceeb036436e065898e411b247bca78/django/conf/global_settings.py#L492). With this, the session is continually saved back to the user agent regardless of session modification. I am not at all opposed to adding this functionality to the crate.

> and the server still happily found the session despite the time being long overdue

Something isn't working as we'd expect. You mention `MokaStore` and `MemoryStore`. Both filter out expired sessions as we can see [here](https://github.com/maxcountryman/tower-sessions/blob/f3a6c911942e02a993eb68abfebfc57ad8995205/src/moka_store.rs#L54) and [here](https://github.com/maxcountryman/tower-sessions/blob/f3a6c911942e02a993eb68abfebfc57ad8995205/src/memory_store.rs#L35), respectively.

Do you have a pared down example you could share so we can investigate together?

**Comment by martinetd** [comment]
Thanks for the quick reply!

> Correct. We follow the Django semantics here, which set a modified flag only when the session is updated. In other words, activity depends on something happening with the session, by default.

Ok, I was assuming session.get() would be considered activity enough (we're checking the user is logged in on every request), but the comment you pointed at is clear enough only modifications are considered so in the current code I'd need to add a dummy set or something to emulate this behaviour.
I don't particularly need a "save every request" feature as long as it's clear; I guess it's more a matter of defining what "activity" means as the "Expire on inactivity." rustdoc comment leaves room for interpetation.

>>  and the server still happily found the session despite the time being long overdue
> 
> Something isn't working as we'd expect. You mention MokaStore and MemoryStore. Both filter out expired sessions as we can see [here](https://github.com/maxcountryman/tower-sessions/blob/f3a6c911942e02a993eb68abfebfc57ad8995205/src/moka_store.rs#L54) and [here](https://github.com/maxcountryman/tower-sessions/blob/f3a6c911942e02a993eb68abfebfc57ad8995205/src/memory_store.rs#L35), respectively.
>
> Do you have a pared down example you could share so we can investigate together?

This looks as simple as I could make it, could reproduce with both memory store and moka store (I was under the impression that this was normal for memory store from https://github.com/maxcountryman/tower-sessions/discussions/33 ; but the code you pointed at should check expiry, right..)

Cargo.toml
```
[package]
name = "t"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
axum-server = "0.5.1"
time = "0.3.30"
tokio = { version = "1.34.0", features = ["full"] }
tower = "0.4.13"
tower-sessions = { version = "0.4.2", features = ["moka", "moka-store"] }
```

src/main.rs
```rust
use axum::error_handling::HandleErrorLayer;
use axum::{http::StatusCode, response::IntoResponse, routing::get, BoxError, Router};
use std::net::SocketAddr;
use time::Duration;
use tower::ServiceBuilder;
use tower_sessions::{Expiry, SessionManagerLayer, Session};
use tower_sessions::MokaStore;
use tower_sessions::MemoryStore;

async fn login(session: Session) -> impl IntoResponse {
    if session.insert("login", true).is_err() {
        "Session insert error"
    } else {
        "Hello"
    }
}

async fn check(session: Session) -> impl IntoResponse {
    if !session
        .get::<bool>("login")
        .unwrap_or(Some(false))
        .unwrap_or(false)
    {
        "Not logged in"
    } else {
        "Ok, you're in"
    }
}

#[tokio::main]
async fn main() {
    let session_store = MokaStore::new(None);
//    let session_store = MemoryStore::default();
    let session_service = ServiceBuilder::new()
        .layer(HandleErrorLayer::new(|_: BoxError| async {
            StatusCode::BAD_REQUEST
        }))
        .layer(
            SessionManagerLayer::new(session_store)
                .with_secure(false)
                .with_expiry(Expiry::OnInactivity(Duration::seconds(10))),
        );

    let app = Router::new()
        .route("/login", get(login))
        .route("/check", get(check))
        .layer(session_service);

    let addr = "[::]:1234".parse().unwrap();
    axum_server::bind(addr)
        .serve(app.into_make_service_with_connect_info::<SocketAddr>())
        .await
        .unwrap();
}
```

```
# login
$ curl -v http://127.0.0.1:1234/login
...
< set-cookie: tower.sid=63999683-b375-4eb3-af7a-87da1b91b3ab; HttpOnly; SameSite=Strict; Path=/; Max-Age=9
< date: Sat, 11 Nov 2023 05:17:32 GMT
Hello

# cookie works
$ curl -v -H "Cookie: tower.sid=63999683-b375-4eb3-af7a-87da1b91b3ab" http://127.0.0.1:1234/check
> Cookie: tower.sid=63999683-b375-4eb3-af7a-87da1b91b3ab
...
< date: Sat, 11 Nov 2023 05:17:41 GMT
Ok, you're in

# same cookie 20s later (longer than 10s expiry time)
$ curl -v -H "Cookie: tower.sid=63999683-b375-4eb3-af7a-87da1b91b3ab" http://127.0.0.1:1234/check
> Cookie: tower.sid=63999683-b375-4eb3-af7a-87da1b91b3ab
< date: Sat, 11 Nov 2023 05:18:01 GMT
Ok, you're in

# different cookie
$ curl -v -H "Cookie: tower.sid=63999683-b375-4eb3-af7a-87da1b91b3ac" http://127.0.0.1:1234/check
> Cookie: tower.sid=63999683-b375-4eb3-af7a-87da1b91b3ac
< set-cookie: tower.sid=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0; Expires=Fri, 11 Nov 2022 05:18:05 GMT
Not logged in
```

**Comment by maxcountryman** [comment]
Thank you, that was very helpful.

We've got a fix in #82 now and once that builds I'll publish a new release.

**Comment by martinetd** [comment]
Thanks!
So the problem was that expiry_date() was always based on current timestamp because modified_at wasn't set yet and expiry_date() would return a time relative to query time, which you wouldn't notice it with examples that modify the session at least once... I've confirmed v0.4.3 checks expiration as expected with Memory and Moka stores and OnInactivity.
(It might be possible to not store redundant information by just changing modified_at to be initialized at creation's timestamp, but a quick check of other stores shows they literally all store the expiry date separately like you just did so it's good to be coherent there. By the way, that means "session expires" will behave as browser session expires or two weeks from now -- I guess that's ok as well given it's how it behaved in other stores)

I've also confirmed the cookie is sent to the client again with a fresh max-age if the session is actually modified (a dummy insert that actually changes the value, e.g. counter or some flip-flop); I don't actually need this so this was just validation but that settles the other part of my issue.

This just leaves the perhaps improving documentation bit (not clear to me how to use absolute timestamps and definition of inactivity), I'll let you deal with that as you see fit.
Feel free to close this anytime :)

**Comment by maxcountryman** [comment]
0.4.3 includes some updates to the docs as well--let me know if you feel like that's clearer now.

Since it sounds like this is working as expected now, I'll close.

**Comment by martinetd** [comment]
> 0.4.3 includes some updates to the docs as well--let me know if you feel like that's clearer now.

Ah, I hadn't seen 49ed1e95bdf3305c198b62fbc80386b8e05945fa
This looks clear enough to me, thanks!
