### ISSUE TITLE
Expiry::AtDateTime behaviour may be surprising

### ISSUE THREAD

**Issue by kamadorueda** [maxcountryman/tower-sessions#77]
While it works as intended and documented, if you set an Expiry::AtDateTime, all sessions after that date time will be issued with negative max-age. This means no sessions will be issued after that as they have already expired

The story behind this comment is that I configured it like `AtDateTime(now + 5 minutes)`, which means my server will stop issuing sessions after 5 minutes of starting, and I failed to realize that it was indeed not a desirable behavior. I think other users may make the same mistake and thus could be useful to document it with a warning (or just remove it from the use cases)

**Comment by maxcountryman** [comment]
Thank for mentioning this.

Typically the way applications would use this is by setting some timestamp in the future as you have and then manually extending that window via `[set_expiry`](https://docs.rs/tower-sessions/latest/tower_sessions/struct.Session.html#method.set_expiry). This gives applications complete control over the conditions for extending a session.

This semantic [mirrors the Django session middleware](https://docs.djangoproject.com/en/4.2/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase.set_expiry) which we are explicitly attempting to support here.

However, this is good evidence that our documentation is lacking and I agree that ensuring users don't run into this with some kind of better illustration is important here.

**Comment by maxcountryman** [comment]
Looking at [the spec](https://httpwg.org/specs/rfc6265.html#max-age-attribute), I don't think we should be setting a negative `Max-Age`, so that's also a bug. Thank you again for reporting this.

**Comment by maxcountryman** [comment]
I believe we've addressed this now. Please let me know if you still find this confusing based on the latest doc updates.
