### ISSUE TITLE
Application Deadlock On v0.4.2

### ISSUE THREAD

**Issue by DominicWrege** [maxcountryman/tower-sessions#84]
I am not sure what the exact cause is, but it is very easy to get a deadlock.

It does not matter which store I use.

- PostgresStore after a couple of repaid request
- with MokaStore and CachingSessionStore after 30 minutes
-  MemoryStore 30 minutes

I tried to diagnose the issue, tokio-console, but that didn't help.

Which information do you need for better investigating this issue?

**Comment by maxcountryman** [comment]
Can you provide a pared down example application that demonstrates the issue you're running into?

**Comment by DominicWrege** [comment]
Okay this is an issue with PostgresStore. 

I will close this one and create a new specific issue. Maybe later reference a sample project.
