### ISSUE TITLE
SessionStore::delete called even if the session was never saved

### ISSUE THREAD

**Issue by bikeshedder** [maxcountryman/tower-sessions#89]
When writing my own `SessionStore` based on `deadpool-postgres` I found that `SessionStore::delete` is called for every new session. Even those which have not been saved. This results in needless DB roundtrips for non-logged-in users:

This is the log output for such request:

```
2023-11-14T21:31:04.045718Z TRACE session_middleware: tower_sessions::service: loaded_sessions=0
2023-11-14T21:31:04.045790Z DEBUG session_middleware: tower_sessions::service: created new session
2023-11-14T21:31:04.045937Z DEBUG session_middleware{session.id="6ef1555a-c7f1-4027-a539-c12dca148d6e"}: tower_sessions::service: deleted
```

Those outputs are generated here...

https://github.com/maxcountryman/tower-sessions/blob/2749adb466d320ce07c523b1ce57854ac6384670/tower-sessions-core/src/service.rs#L165-L170

...and here:

https://github.com/maxcountryman/tower-sessions/blob/2749adb466d320ce07c523b1ce57854ac6384670/tower-sessions-core/src/service.rs#L180-L185

Looking at the `Session.deleted()` implementation I can see why this is happening. The current implementation doesn't keep track if the session was every saved. This results in `SessionStore::delete` calls for every request that doesn't modify the session.

**Comment by maxcountryman** [comment]
Hi, thanks for reporting this. Perhaps we need to gate [this inovation](https://github.com/maxcountryman/tower-sessions/blob/2749adb466d320ce07c523b1ce57854ac6384670/tower-sessions-core/src/service.rs#L191) on `is_empty` being `false`.

**Comment by bikeshedder** [comment]
Regarding the states of the session I think Django has a very clean implementation that could be copied 1:1 for `tower-sessions`: https://github.com/django/django/blob/main/django/contrib/sessions/middleware.py

All that's needed are three booleans in the session itself:

- accessed
- modified
- empty

Additionally the implementation needs to know if the session cookie is set.

With this information the decision of when to save, update or delete is very easy to make.

The current implementation of `tower-session` seams a bit convoluted in that regards. I can only guess that the reason for that is the support for persistent in-memory sessions. That also explains the need for so many mutexes and the `dashmap` crate. I do wonder how that works when using a session storage that loads the sessions from a database?

**Comment by maxcountryman** [comment]
> The current implementation of tower-session seams a bit convoluted in that regards.

There's actually another reason for this, which is probably not so obvious: Django interacts with the store in realtime, not within the middleware. This complicates things quite a bit, as it turns out, because we have to do lifecycle management Django simply does not do.

**Comment by maxcountryman** [comment]
> All that's needed are three booleans in the session itself:
> 
> * accessed
> * modified
> * empty

We could extend session to support something like `accessed_at` or an `accessed` boolean (but this isn't really the right term, we really mean saved, not accessed, because we specifically need to handle the case where we remove the session from the store after it's been saved to it).

Django avoids this by deleting directly from the store when e.g. `flush` is called. However, our session isn't aware of the store directly so this is where our code diverges and a good deal more complexity is introduced.

**Comment by maxcountryman** [comment]
I think there's a simple enough solution here: we can check for the presence of a cookie to determine if we've ever issued `Set-Cookie` in the past--this appears to be what Django is doing, albeit they're able to capitalize on having access to the store.

Taking a step back, I'm open to improving this design such that we can simplify the implementation, inclusive of breaking changes. For instance, maybe it's worth considering if the store and session should be housed together such that it is possible to delete directly from the session API.

**Comment by bikeshedder** [comment]
> Django avoids this by deleting directly from the store when e.g. flush is called. However, our session isn't aware of the store directly so this is where our code diverges and a good deal more complexity is introduced.

That is only true when using the `db` backend and not even necessary. Django does make the entire `Session` object pluggable but that is merely out of convenience and due to the dynamic nature of Python. The Django code is a bit weird in that regards as the `session` object is just an instance of the `SessionStore`.

While it is possible to access the store specific session methods I'd consider them very bad practice. The `flush` method indeed calls the `delete` method but it would be fine to delay the deletion until the middleware. imho. the design in Django would be a bit nicer if that was indeed the case. I can only assume that they wanted to invalidate the session as fast as possible without having to wait for the response to be sent.

**Comment by maxcountryman** [comment]
I'm open to simplifying our implementation--PRs and very welcome. 🤗

**Comment by maxcountryman** [comment]
I think we've addressed the original issue, so I'll close this for now.
